server:
  port: 8080
  
spring:
  database:
    driverClassName: com.mysql.jdbc.Driver
  datasource:
    validateQuery: SELECT 1
    url: 
    username: 
    password: 
  jpa:
    show-sql: true
    hibernate:      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        default_scheme: codecom1_test